Repository izone00/webserv, pull requests merged in 2023-08, with the labels that each got.

#11 Feature/#5 configparser 만들기
  Makefile
  include/ConfigParser.hpp
  include/ConfigUtils.hpp
  include/DerivTree.hpp
  include/Modules.hpp
  srcs/ConfigParser.cpp
  srcs/DerivTree.cpp
Labels: enhancement

#12 Feature/#6 server 만들기
  .vscode/settings.json
  include/Server.hpp
  srcs/Server.cpp
Labels: enhancement

#10 Feature/#4 server handler 만들기
  include/ServerHandler.hpp
  srcs/ServerHandler.cpp
Labels: enhancement

#18 Feat: MethodExecutor 구현
  Makefile
  include/EnvironmentValues.hpp
  include/HttpMessage.hpp
  include/HttpRequestMessage.hpp
  include/HttpResponseBuilder.hpp
  include/HttpResponseMessage.hpp
  include/MethodExecutor.hpp
  include/Utils.hpp
  srcs/EnvironmentValues.cpp
  srcs/HttpMessage.cpp
  srcs/HttpRequestMessage.cpp
  srcs/HttpResponseBuilder.cpp
  srcs/HttpResponseMessage.cpp
  srcs/MethodExecutor.cpp
  srcs/Utils.cpp
Labels: enhancement

#21 Feature/#16 컴파일에러 수정
  .vscode/settings.json
  Makefile
  include/Client.hpp
  include/Server.hpp
  include/ServerHandler.hpp
  srcs/Client.cpp
  srcs/Server.cpp
  srcs/ServerHandler.cpp
  srcs/main.cpp
Labels: bug

#24 Feature/#8 config 만들기
  Makefile
  include/Config.hpp
  include/DerivTree.hpp
  include/LocationConfig.hpp
  include/Modules.hpp
  include/ServerConfig.hpp
  srcs/Config.cpp
  srcs/ConfigParser.cpp
  srcs/DerivTree.cpp
  srcs/LocationConfig.cpp
  srcs/ServerConfig.cpp
Labels: enhancement

#30 Feat: cgi모듈 구현
  include/DerivTree.hpp
  include/EnvironmentValues.hpp
  include/LocationConfig.hpp
  include/Modules.hpp
  srcs/DerivTree.cpp
  srcs/EnvironmentValues.cpp
  srcs/LocationConfig.cpp
Labels: enhancement

#33 autoindex, client_max_body, accept_method 구현
  include/DerivTree.hpp
  include/EnvironmentValues.hpp
  include/LocationConfig.hpp
  include/Modules.hpp
  srcs/DerivTree.cpp
  srcs/EnvironmentValues.cpp
  srcs/LocationConfig.cpp
Labels: enhancement

#40 디버그용 print제거
  include/Config.hpp
  include/DerivTree.hpp
  include/LocationConfig.hpp
  include/Modules.hpp
  include/ServerConfig.hpp
  srcs/ConfigParser.cpp
Labels: refactoring

#42 Feat: CgiMethodExceutor 구현
  include/CgiMethodExecutor.hpp
  include/ICgiScriptor.hpp
  include/PythonScriptor.hpp
  srcs/CgiMethodExecutor.cpp
Labels: enhancement

#41 Feature/#32 소켓 관련 클래스 구조 변경
  .vscode/settings.json
  include/Client.hpp
  include/Server.hpp
  include/ServerHandler.hpp
  srcs/Client.cpp
  srcs/Server.cpp
  srcs/ServerHandler.cpp
Labels: bug, wontfix

#38 Feature/#36 header adder클래스생성 및 default method executor 보완
  Makefile
  include/CgiMethodExecutor.hpp
  include/DefaultMethodExecutor.hpp
  include/ExtendedResponseHeaderAdder.hpp
  include/HttpRequestMessage.hpp
  include/HttpResponseBuilder.hpp
  include/HttpResponseMessage.hpp
  include/IMethodExecutor.hpp
  include/LocationConfig.hpp
  include/ResponseHeaderAdder.hpp
  srcs/CgiMethodExecutor.cpp
  srcs/DefaultMethodExecutor.cpp
  srcs/ExtendedResponseHeaderAdder.cpp
  srcs/HttpRequestMessage.cpp
  srcs/HttpResponseBuilder.cpp
  srcs/HttpResponseMessage.cpp
  srcs/LocationConfig.cpp
  srcs/ResponseHeaderAdder.cpp
  srcs/main.cpp
Labels: enhancement

#45 Fix: error 해결~
  Makefile
  YoupiBanane/Yeah/not_happy.bad_extension
  YoupiBanane/nop/other.pouic
  YoupiBanane/nop/youpi.bad_extension
  YoupiBanane/youpi.bad_extension
  YoupiBanane/youpi.bla
  html/index.html
  include/config/Config.hpp
  include/config/ConfigParser.hpp
  include/config/ConfigUtils.hpp
  include/config/DerivTree.hpp
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  include/config/ServerConfig.hpp
  include/http/CgiMethodExecutor.hpp
  include/http/DefaultMethodExecutor.hpp
  include/http/ExtendedResponseHeaderAdder.hpp
  include/http/HttpMessage.hpp
  include/http/HttpRequestMessage.hpp
  include/http/HttpResponseBuilder.hpp
  include/http/HttpResponseMessage.hpp
  include/http/IMethodExecutor.hpp
  include/http/ResponseHeaderAdder.hpp
  include/http/Utils.hpp
  include/http/WebservValues.hpp
  include/server/Client.hpp
  include/server/Server.hpp
  include/server/ServerHandler.hpp
  srcs/config/Config.cpp
  srcs/config/ConfigParser.cpp
  srcs/config/DerivTree.cpp
  srcs/config/LocationConfig.cpp
  srcs/config/ServerConfig.cpp
  srcs/http/CgiMethodExecutor.cpp
  srcs/http/DefaultMethodExecutor.cpp
  srcs/http/ExtendedResponseHeaderAdder.cpp
  srcs/http/HttpMessage.cpp
  srcs/http/HttpRequestMessage.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/HttpResponseMessage.cpp
  srcs/http/ResponseHeaderAdder.cpp
  srcs/http/Utils.cpp
  srcs/http/WebservValues.cpp
  srcs/main.cpp
  srcs/server/Client.cpp
  srcs/server/Server.cpp
  srcs/server/ServerHandler.cpp
  tester.conf
Labels: bug

#51 Feature/#46 server 추가 구현
  Makefile
  html/test.py
  include/http/CgiMethodExecutor.hpp
  include/http/DefaultMethodExecutor.hpp
  include/http/IMethodExecutor.hpp
  include/http/WebservValues.hpp
  include/server/Client.hpp
  include/server/Server.hpp
  srcs/config/LocationConfig.cpp
  srcs/http/CgiMethodExecutor.cpp
  srcs/http/DefaultMethodExecutor.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/WebservValues.cpp
  srcs/server/Client.cpp
  srcs/server/Server.cpp
  srcs/server/ServerHandler.cpp
  tester.conf
Labels: bug, enhancement

#50 Fix: cgi모듈 방식 on/off로 수정
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  srcs/config/DerivTree.cpp
  srcs/config/LocationConfig.cpp
Labels: fix

#61 Feat: Linux 가능
  Makefile
  html/test.py
  include/http/CgiMethodExecutor.hpp
  include/http/DefaultMethodExecutor.hpp
  include/http/IMethodExecutor.hpp
  include/server/Client.hpp
  include/server/ServerHandler.hpp
  srcs/http/DefaultMethodExecutor.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/WebservValues.cpp
  srcs/main.cpp
  srcs/server/Client.cpp
  srcs/server/ServerHandler.cpp
  tester.conf
Labels: enhancement, wontfix

#63 Fix: Bug: 모듈 없거나 LocConfMap 비었을시 에러 처리
  include/config/Modules.hpp
  include/config/ServerConfig.hpp
  srcs/config/LocationConfig.cpp
  srcs/config/ServerConfig.cpp
Labels: fix

#66 Fix: 다양한 에러 해결 및 ReponseBuilder와 HttpRequestMessage에 플래그 변수 추가
  Makefile2
  html/notReadable
  html/post_body/eunjilee
  html/post_body/notDeletable
  html/readable
  include/config/Config.hpp
  include/config/ConfigParser.hpp
  include/config/DerivTree.hpp
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  include/config/ServerConfig.hpp
  include/http/HttpRequestMessage.hpp
  include/http/HttpResponseBuilder.hpp
  include/http/Utils.hpp
  include/server/Client.hpp
  srcs/config/Config.cpp
  srcs/config/ConfigParser.cpp
  srcs/config/DerivTree.cpp
  srcs/config/LocationConfig.cpp
  srcs/config/ServerConfig.cpp
  srcs/http/HttpRequestMessage.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/ResponseHeaderAdder.cpp
  srcs/http/ServerErrors.cpp
  srcs/http/Utils.cpp
  srcs/main.cpp
  srcs/server/Client.cpp
  tester.conf
Labels: fix

#75 location "/" 일때 버그 수정과 코드리팩토링
  Makefile
  include/config/Config.hpp
  include/config/ConfigParser.hpp
  include/config/ConfigUtils.hpp
  include/config/DirectiveTree.hpp
  include/config/Modules.hpp
  include/config/ServerConfig.hpp
  srcs/config/ConfigParser.cpp
  srcs/config/DerivTree.cpp
  srcs/config/DirectiveTree.cpp
  srcs/config/Modules.cpp
  srcs/config/ServerConfig.cpp
Labels: bug, refactoring, style

#78 Feature/#67 메서드 추가 구현 및 에러 고치기 및 통합테스트 진행
  Makefile
  html/auto/promise
  include/http/CgiMethodExecutor.hpp
  include/http/DefaultMethodExecutor.hpp
  include/http/HttpRequestMessage.hpp
  include/http/HttpResponseBuilder.hpp
  include/http/HttpResponseMessage.hpp
  include/http/IMethodExecutor.hpp
  include/http/ResponseHeaderAdder.hpp
  include/http/ResponseStatusManager.hpp
  include/http/ServerAutoIndexSimulator.hpp
  srcs/http/CgiMethodExecutor.cpp
  srcs/http/DefaultMethodExecutor.cpp
  srcs/http/HttpRequestMessage.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/HttpResponseMessage.cpp
  srcs/http/ResponseHeaderAdder.cpp
  srcs/http/ResponseStatusManager.cpp
  srcs/http/ServerAutoIndexSimulator.cpp
  srcs/http/WebservValues.cpp
  srcs/main.cpp
  srcs/server/Client.cpp
Labels: bug, enhancement, fix

#79 Feature/#76 error page 지시어 다시 구현 및 cgi 지시어 원래대로 복구
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  srcs/config/LocationConfig.cpp
  srcs/config/Modules.cpp
Labels: enhancement, fix

#81 Feature/#77 server/코드 리펙토링
  .gitignore
  Makefile
  YoupiBanane/directory/Yeah/not_happy.bad_extension
  YoupiBanane/directory/nop/other.pouic
  YoupiBanane/directory/nop/youpi.bad_extension
  YoupiBanane/directory/youpi.bad_extension
  YoupiBanane/directory/youpi.bla
  html/index.py
  html/test.py
  include/http/HttpResponseBuilder.hpp
  include/server/Client.hpp
  srcs/http/CgiMethodExecutor.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/main.cpp
  srcs/server/Client.cpp
  srcs/server/Server.cpp
  srcs/server/ServerHandler.cpp
  tester.conf
Labels: fix

#82 Feat: return 지시어 구현
  include/config/DirectiveTree.hpp
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  srcs/config/DirectiveTree.cpp
  srcs/config/LocationConfig.cpp
  srcs/config/Modules.cpp
Labels: enhancement

#85 Feat: config클래스 소멸자 구현
  include/config/Config.hpp
  include/config/Modules.hpp
  srcs/config/Config.cpp
  srcs/config/DirectiveTree.cpp
  srcs/config/Modules.cpp
Labels: enhancement

#86 Feature/#77 server/코드 리펙토링
  include/config/Config.hpp
  include/config/ConfigParser.hpp
  include/config/ConfigUtils.hpp
  include/config/DirectiveTree.hpp
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  include/config/ServerConfig.hpp
  include/http/CgiMethodExecutor.hpp
  include/http/DefaultMethodExecutor.hpp
  include/http/HttpMessage.hpp
  include/http/HttpRequestMessage.hpp
  include/http/HttpResponseBuilder.hpp
  include/http/HttpResponseMessage.hpp
  include/http/IMethodExecutor.hpp
  include/http/ResponseHeaderAdder.hpp
  include/http/ResponseStatusManager.hpp
  include/http/ServerAutoIndexSimulator.hpp
  include/http/Utils.hpp
  include/http/WebservValues.hpp
  include/server/Client.hpp
  include/server/Server.hpp
  include/server/ServerHandler.hpp
  srcs/config/Config.cpp
  srcs/config/ConfigParser.cpp
  srcs/config/DirectiveTree.cpp
  srcs/config/LocationConfig.cpp
  srcs/config/Modules.cpp
  srcs/config/ServerConfig.cpp
  srcs/http/CgiMethodExecutor.cpp
  srcs/http/DefaultMethodExecutor.cpp
  srcs/http/HttpMessage.cpp
  srcs/http/HttpRequestMessage.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/HttpResponseMessage.cpp
  srcs/http/ResponseHeaderAdder.cpp
  srcs/http/ResponseStatusManager.cpp
  srcs/http/ServerAutoIndexSimulator.cpp
  srcs/http/Utils.cpp
  srcs/http/WebservValues.cpp
  srcs/main.cpp
  srcs/server/Client.cpp
  srcs/server/Server.cpp
  srcs/server/ServerHandler.cpp
  tester.conf
Labels: enhancement

#88 Bug: 코드 리팩토링 머지 후 컴파일 오류 해결 및 다시 리팩토링
  include/config/Config.hpp
  include/config/DirectiveTree.hpp
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  srcs/config/DirectiveTree.cpp
  srcs/config/LocationConfig.cpp
  srcs/config/Modules.cpp
Labels: bug

#89 Feature/#83 http request builder class 추가 및 http response builder class 변경
  Custom/customErrPage/LGTM!!!!
  Custom/customErrPage/index.html
  Makefile
  html/readable
  html/test2.py
  include/http/HttpRequestBuilder.hpp
  include/http/HttpRequestMessage.hpp
  include/http/HttpResponseBuilder.hpp
  include/http/HttpResponseMessage.hpp
  include/http/Utils.hpp
  include/server/Client.hpp
  srcs/config/LocationConfig.cpp
  srcs/http/HttpRequestBuilder.cpp
  srcs/http/HttpRequestMessage.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/HttpResponseMessage.cpp
  srcs/http/ResponseHeaderAdder.cpp
  srcs/http/ResponseStatusManager.cpp
  srcs/http/Utils.cpp
  srcs/main.cpp
  srcs/server/Client.cpp
  tester.conf
Labels: bug, enhancement, fix

#91 Feature/#90 리다이렉트 구현 및 통합테스트
  Custom/customErrPage/LGTM
  Custom/customErrPage/index.html
  Makefile2
  html/auto/promise
  include/http/DefaultMethodExecutor.hpp
  include/http/HttpMessage.hpp
  include/http/HttpRequestBuilder.hpp
  include/http/HttpRequestMessage.hpp
  include/http/HttpResponseBuilder.hpp
  include/http/HttpResponseMessage.hpp
  include/http/ResponseHeaderAdder.hpp
  include/http/ResponseStatusManager.hpp
  include/http/Utils.hpp
  include/server/Client.hpp
  srcs/http/HttpMessage.cpp
  srcs/http/HttpRequestBuilder.cpp
  srcs/http/HttpRequestMessage.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/HttpResponseMessage.cpp
  srcs/http/ResponseHeaderAdder.cpp
  srcs/http/ResponseStatusManager.cpp
  srcs/http/ServerAutoIndexSimulator.cpp
  srcs/http/Utils.cpp
  srcs/server/Client.cpp
Labels: bug, enhancement, fix

#94 Fix: return지시어 인식 안되는 오류 해결
  srcs/config/LocationConfig.cpp
Labels: bug

#98 Fix: Config 객체 delete안해도 되도록 수정
  Makefile
  include/config/Config.hpp
  include/config/ConfigParser.hpp
  srcs/config/Config.cpp
  srcs/config/ConfigParser.cpp
  srcs/main.cpp
  srcs/server/ServerHandler.cpp
Labels: fix

#103 Fix/#92 통합 테스트 및 문제점 개선하기2
  srcs/http/DefaultMethodExecutor.cpp
  srcs/http/HttpRequestBuilder.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/ResponseHeaderAdder.cpp
  srcs/http/Utils.cpp
Labels: bug, fix

#101 Feat: Connection Close 구현
  include/server/Client.hpp
  srcs/main.cpp
  srcs/server/Client.cpp
  srcs/server/ServerHandler.cpp
Labels: enhancement

#100 Fix: config, server 파일 c++98컴파일 오류 해결
  Makefile
  include/config/Modules.hpp
  include/http/CgiMethodExecutor.hpp
  srcs/config/DirectiveTree.cpp
  srcs/config/LocationConfig.cpp
  srcs/config/Modules.cpp
  srcs/http/CgiMethodExecutor.cpp
  srcs/server/ServerHandler.cpp
  tester.conf
Labels: fix

#105 Fix: http
  include/config/LocationConfig.hpp
  include/config/Modules.hpp
  include/http/HttpRequestBuilder.hpp
  include/http/HttpResponseBuilder.hpp
  include/http/WebservValues.hpp
  srcs/config/LocationConfig.cpp
  srcs/config/Modules.cpp
  srcs/http/DefaultMethodExecutor.cpp
  srcs/http/HttpRequestBuilder.cpp
  srcs/http/HttpResponseBuilder.cpp
  srcs/http/WebservValues.cpp
  srcs/server/ServerHandler.cpp
Labels: fix
